# Generated by Django 5.2 on 2025-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmap', '0002_remove_medicine_price_inventorymed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='generic',
            field=models.CharField(max_length=100),
        ),
    ]
